name = "Chevie"
uuid = "367f69f0-ca63-11e8-2372-438b29340c1b"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.4"

[deps]
Combinat = "a6b051d1-fc4b-4ede-b53e-347fa9fb9a74"
CycPols = "05fb067e-2cd1-4891-b41e-2c136232fb98"
CyclotomicNumbers = "c380f8b6-65b3-4789-a31b-7d6b5dc6d4c5"
FiniteFields = "bbb6641c-4b7b-4120-8cb1-379a8ed7c848"
FinitePosets = "580d1d9c-67b1-4c59-872e-f12456ffb9fa"
GenLinearAlgebra = "2304d612-645f-44c0-913c-a25a709b015d"
GenericDecMats = "a98d1166-8d3f-4eaf-b2a4-26e52ad22d9c"
GroupPresentations = "e70aea02-d551-4d4a-88dc-a60a3b79560b"
LaurentPolynomials = "10b2801c-d482-41ed-a506-4a825c59e3da"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatInt = "f23b31af-f0ea-4208-b2e0-bbfc29c446c9"
ModuleElts = "4249f315-58d4-4c46-b324-3577fc7dfca0"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d" 
PermGroups = "0b63354f-98d5-4b2f-8b91-7408084ca26b"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
PuiseuxPolynomials = "f53aee1f-40be-4d16-bc74-7d339eee78ec"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SignedPerms = "87930f55-5467-4ad4-bf41-f0163ea2f44f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UsingMerge = "b01ca8d2-7fff-4612-bd8c-d9d20281f780"

[weakdeps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"

[extensions]
Gap4 = "GAP"

[compat]
Combinat = "0.1.1"
CycPols = "0.1.3"
CyclotomicNumbers = "0.1.6"
FiniteFields = "0.1.1"
FinitePosets = "0.1.4"
GAP = "0.10, 1"
GenLinearAlgebra = "0.1.2"
GenericDecMats = "0.1"
GroupPresentations = "0.1.1"
LaurentPolynomials = "0.1.1"
LinearAlgebra = "1"
MatInt = "0.1.2"
ModuleElts = "0.1.3"
OrderedCollections = "1"
PermGroups = "0.2.17, 0.3"
Primes = "0.5.4, 0.6"
PuiseuxPolynomials = "0.1.5"
Reexport = "1"
SignedPerms = "0.1.2"
SparseArrays = "1"
Test = "1"
UsingMerge = "0.0.6, 0.0.7"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
