name = "Gapjm"
uuid = "367f69f0-ca63-11e8-2372-438b29340c1b"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.0"

[compat]
julia = "1.6"
Primes = "0.5.3, 0.6"
UsingMerge = "0.0.5,0.0.6"
ModuleElts = "0.0.7,0.0.8,0.0.9"
LaurentPolynomials = "0.0.5, 0.0.6,0.0.7,0.0.8,0.0.9"
PuiseuxPolynomials = "0.1"
PermGroups = "0.2, 0.3"
CyclotomicNumbers = "0.1"
GenericDecMats = "0.1"
Combinat = "0.0.3, 0.0.4"
GAP = "0.8, 0.9, 1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
UsingMerge = "b01ca8d2-7fff-4612-bd8c-d9d20281f780"
ModuleElts = "4249f315-58d4-4c46-b324-3577fc7dfca0"
LaurentPolynomials = "10b2801c-d482-41ed-a506-4a825c59e3da"
PuiseuxPolynomials = "f53aee1f-40be-4d16-bc74-7d339eee78ec"
CyclotomicNumbers = "c380f8b6-65b3-4789-a31b-7d6b5dc6d4c5"
Combinat = "a6b051d1-fc4b-4ede-b53e-347fa9fb9a74"
PermGroups = "0b63354f-98d5-4b2f-8b91-7408084ca26b"
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
GenericDecMats = "a98d1166-8d3f-4eaf-b2a4-26e52ad22d9c"
